"""create_authentication_tables

Revision ID: c242ae284851
Revises:
Create Date: 2024-04-19 09:47:59.139959

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c242ae284851"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "db_user_role",
        sa.Column("id", sa.Integer(), nullable=False, comment="user_role id"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="user id"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="admin_role id"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_credential",
        sa.Column("id", sa.Integer(), nullable=False, comment="event_credential id"),
        sa.Column(
            "event_name", sa.String(length=64), nullable=False, comment="event name"
        ),
        sa.Column("remark", sa.String(length=100), nullable=True, comment="备注"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_credential_event_name"),
        "event_credential",
        ["event_name"],
        unique=False,
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False, comment="permission id"),
        sa.Column(
            "identifier", sa.String(length=64), nullable=False, comment="权限标识"
        ),
        sa.Column(
            "permission_name", sa.String(length=32), nullable=False, comment="权限名称"
        ),
        sa.Column("remark", sa.String(length=100), nullable=True, comment="备注"),
        sa.Column(
            "enabled",
            sa.SMALLINT(),
            nullable=True,
            comment="是否启用, 0 禁用 1 启用 2 废弃",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_identifier"), "permission", ["identifier"], unique=False
    )
    op.create_table(
        "permission_role",
        sa.Column("id", sa.Integer(), nullable=False, comment="permission_role id"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色标识"),
        sa.Column("permission_id", sa.Integer(), nullable=False, comment="权限标识"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False, comment="role id"),
        sa.Column(
            "identifier", sa.String(length=64), nullable=False, comment="权限标识"
        ),
        sa.Column(
            "role_name", sa.String(length=32), nullable=False, comment="角色名称"
        ),
        sa.Column(
            "enabled",
            sa.SMALLINT(),
            nullable=True,
            comment="是否启用, 0 禁用 1 启用 2 废弃",
        ),
        sa.Column("remark", sa.String(length=100), nullable=True, comment="备注"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_identifier"), "role", ["identifier"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False, comment="user id"),
        sa.Column("username", sa.String(length=64), nullable=True, comment="用户名"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="手机号"),
        sa.Column("email", sa.String(length=100), nullable=True, comment="邮箱"),
        sa.Column("password", sa.String(length=32), nullable=False, comment="密码"),
        sa.Column(
            "status", sa.SMALLINT(), nullable=False, comment="状态 0 正常 1 禁用"
        ),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("update_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_token",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="user token id"),
        sa.Column("token", sa.String(length=32), nullable=False, comment="token"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_token")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_identifier"), table_name="role")
    op.drop_table("role")
    op.drop_table("permission_role")
    op.drop_index(op.f("ix_permission_identifier"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_event_credential_event_name"), table_name="event_credential")
    op.drop_table("event_credential")
    op.drop_table("db_user_role")
    # ### end Alembic commands ###
